# Generated by Django 2.0.1 on 2018-02-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.Barrage')),
            ],
        ),
        migrations.RemoveField(
            model_name='fileup',
            name='profile',
        ),
        migrations.AddField(
            model_name='fileup',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='up.Instrument'),
        ),
    ]
