# Generated by Django 2.0.1 on 2018-05-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0004_auto_20180512_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField()),
                ('date', models.DateField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.Profile')),
            ],
        ),
    ]
